// turkey-provinces.geojson dosyasindaki "name" alanlarina (81 il) gore
// 7 cografi bolge eslestirmesi. Backend'deki PROVINCE_TO_REGION ile ayni
// bolunumu kullanir; sadece "Afyon" yazimi GeoJSON kaynagiyla eslesecek
// sekilde "Afyonkarahisar" yerine kullanilir.
export const PROVINCE_TO_REGION = {
  // Marmara
  Balıkesir: "marmara",
  Bilecik: "marmara",
  Bursa: "marmara",
  Çanakkale: "marmara",
  Edirne: "marmara",
  İstanbul: "marmara",
  Kırklareli: "marmara",
  Kocaeli: "marmara",
  Sakarya: "marmara",
  Tekirdağ: "marmara",
  Yalova: "marmara",
  // Ege
  Afyon: "ege",
  Aydın: "ege",
  Denizli: "ege",
  İzmir: "ege",
  Kütahya: "ege",
  Manisa: "ege",
  Muğla: "ege",
  Uşak: "ege",
  // Akdeniz
  Adana: "akdeniz",
  Antalya: "akdeniz",
  Burdur: "akdeniz",
  Hatay: "akdeniz",
  Isparta: "akdeniz",
  Kahramanmaraş: "akdeniz",
  Mersin: "akdeniz",
  Osmaniye: "akdeniz",
  // Ic Anadolu
  Aksaray: "icAnadolu",
  Ankara: "icAnadolu",
  Çankırı: "icAnadolu",
  Eskişehir: "icAnadolu",
  Karaman: "icAnadolu",
  Kayseri: "icAnadolu",
  Kırıkkale: "icAnadolu",
  Kırşehir: "icAnadolu",
  Konya: "icAnadolu",
  Nevşehir: "icAnadolu",
  Niğde: "icAnadolu",
  Sivas: "icAnadolu",
  Yozgat: "icAnadolu",
  // Karadeniz
  Amasya: "karadeniz",
  Artvin: "karadeniz",
  Bartın: "karadeniz",
  Bayburt: "karadeniz",
  Bolu: "karadeniz",
  Çorum: "karadeniz",
  Düzce: "karadeniz",
  Giresun: "karadeniz",
  Gümüşhane: "karadeniz",
  Kastamonu: "karadeniz",
  Karabük: "karadeniz",
  Ordu: "karadeniz",
  Rize: "karadeniz",
  Samsun: "karadeniz",
  Sinop: "karadeniz",
  Tokat: "karadeniz",
  Trabzon: "karadeniz",
  Zonguldak: "karadeniz",
  // Dogu Anadolu
  Ağrı: "doguAnadolu",
  Ardahan: "doguAnadolu",
  Bingöl: "doguAnadolu",
  Bitlis: "doguAnadolu",
  Elazığ: "doguAnadolu",
  Erzincan: "doguAnadolu",
  Erzurum: "doguAnadolu",
  Hakkari: "doguAnadolu",
  Iğdır: "doguAnadolu",
  Kars: "doguAnadolu",
  Malatya: "doguAnadolu",
  Muş: "doguAnadolu",
  Tunceli: "doguAnadolu",
  Van: "doguAnadolu",
  // Guneydogu Anadolu
  Adıyaman: "guneydoguAnadolu",
  Batman: "guneydoguAnadolu",
  Diyarbakır: "guneydoguAnadolu",
  Gaziantep: "guneydoguAnadolu",
  Kilis: "guneydoguAnadolu",
  Mardin: "guneydoguAnadolu",
  Siirt: "guneydoguAnadolu",
  Şanlıurfa: "guneydoguAnadolu",
  Şırnak: "guneydoguAnadolu",
};

export const REGION_ORDER = [
  "marmara",
  "ege",
  "akdeniz",
  "icAnadolu",
  "karadeniz",
  "doguAnadolu",
  "guneydoguAnadolu",
];
